#! /bin/bash 
if type -t wevtutil &> /dev/null 
then
    OS=MSWin
elif type -t scutil &> /dev/null 
then 
    OS=macOS
else
    OS=Linux
fi
echo $OS 

function is_alive_ping() { 
    ping -c 1 $1 > /dev/null 2>&1
    [ $? -eq 0 ] && echo "Node with IP: $i is up."
}

$file
for i in $file
do
is_alive_ping $i & disown 
done
